import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Card } from '../components/common/Card';
import { Badge } from '../components/common/Badge';
import { LoadingSpinner, EmptyState, PageHeader, WarningBanner } from '../components/common/LoadingSpinner';
import { Button } from '../components/common/Button';
import { Modal, FormField, Select, Textarea } from '../components/common/Modal';
import { getEmployees, getAssignments, getOpenShifts, getOpenShiftPickupRequests, getAvailability, createOpenShift, requestOpenShiftPickup, resolveOpenShiftPickupRequest, withdrawOpenShift } from '../services/dataService';
import { formatDate } from '../utils/dateUtils';
import type { Availability, Employee, ShiftAssignment, OpenShiftRequest, OpenShiftPickupRequest, ShiftType } from '../types';

const ICON: Record<ShiftType, string> = { day: '☀', evening: '🌆', night: '🌙' };

export default function OpenShiftsPage() {
  const { currentUser } = useAuth();
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [employees, setEmployees] = useState<Employee[]>([]); const [assignments, setAssignments] = useState<ShiftAssignment[]>([]); const [availability, setAvailability] = useState<Availability[]>([]); const [shifts, setShifts] = useState<OpenShiftRequest[]>([]); const [applications, setApplications] = useState<OpenShiftPickupRequest[]>([]);
  const [placeModal, setPlaceModal] = useState(false); const [shiftId, setShiftId] = useState(''); const [reason, setReason] = useState(''); const [review, setReview] = useState<OpenShiftPickupRequest | null>(null); const [note, setNote] = useState('');
  const isManager = currentUser?.role === 'manager'; const myId = currentUser?.employeeId ?? '';
  const name = (id: string) => employees.find(e => e.id === id)?.name ?? id;
  const assignment = (id: string) => assignments.find(a => a.id === id);
  const forShift = (id: string) => applications.filter(a => a.openShiftId === id).sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  async function load() { try { const [e, a, av, s, p] = await Promise.all([getEmployees(), getAssignments(), getAvailability(), getOpenShifts(), getOpenShiftPickupRequests()]); setEmployees(e); setAssignments(a); setAvailability(av); setShifts(s); setApplications(p); } catch (err) { const message = err && typeof err === 'object' && 'message' in err && typeof err.message === 'string' ? err.message : ''; setError(message.includes('open_shift_pickup_requests') ? 'Open-shift applications need the new Supabase migration. Run supabase/migrations/20260907_open_shift_pickup_queue.sql once, then refresh.' : message || 'Could not load open shifts.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function save(action: () => Promise<void>) { setSaving(true); setError(''); try { await action(); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save your change.'); } finally { setSaving(false); } }
  const pool = shifts.filter(s => s.status === 'open' || s.status === 'requested'); const pending = applications.filter(a => a.status === 'pending'); const history = shifts.filter(s => !pool.includes(s));
  function canPlaceInPool(candidate: ShiftAssignment) {
    return assignments.filter(item => item.date === candidate.date && item.shiftType === candidate.shiftType).length <= 2;
  }
  function dateOffset(date: string, offset: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + offset); return value.toISOString().slice(0, 10); }
  function pickupEligibility(openShift: OpenShiftRequest) {
    const target = assignment(openShift.shiftId); if (!target) return { allowed: false, warnings: ['This shift is no longer available.'] };
    const off = availability.some(item => item.employeeId === myId && item.date === target.date && item.status === 'off');
    const sameDay = assignments.filter(item => item.employeeId === myId && item.date === target.date && item.id !== target.id);
    const names = sameDay.map(item => item.shiftType);
    const required: Record<ShiftType, ShiftType[]> = { day: ['evening'], evening: ['day', 'night'], night: ['evening'] };
    if (off) {
      if (target.shiftType === 'day' && assignments.some(item => item.employeeId === myId && item.date === dateOffset(target.date, -1) && item.shiftType === 'night')) return { allowed: false, warnings: ['Manager assigned you OFF today. You cannot pick a Day shift after working Night shift the previous day.'] };
      if (target.shiftType === 'night' && assignments.some(item => item.employeeId === myId && item.date === dateOffset(target.date, 1) && item.shiftType === 'day')) return { allowed: false, warnings: ['Manager assigned you OFF today. You cannot pick a Night shift before a Day shift the next day.'] };
      return { allowed: true, warnings: ['Manager assigned you OFF on this day. A manager can still approve this pickup.'] };
    }
    const compatible = required[target.shiftType].filter(type => names.includes(type));
    if (compatible.length) return { allowed: true, warnings: [`Already assigned today to ${compatible.map(type => type[0].toUpperCase() + type.slice(1)).join(' or ')} shift.`] };
    const allowedNames = required[target.shiftType].map(type => type[0].toUpperCase() + type.slice(1)).join(' or ');
    return { allowed: false, warnings: [names.length ? `You are assigned to ${names.map(type => type[0].toUpperCase() + type.slice(1)).join(' and ')} shift today. Only ${allowedNames} shift employees or manager-assigned OFF employees can apply.` : `Only ${allowedNames} shift employees or manager-assigned OFF employees can apply.`] };
  }
  if (loading) return <LoadingSpinner label="Loading open shifts…" />;
  return <div className="space-y-5">
    <PageHeader title="Open Shift Pool" subtitle={`${pool.length} open · ${pending.length} applications awaiting approval`} action={!isManager && <Button size="sm" icon="◯" onClick={() => setPlaceModal(true)}>Place Shift</Button>} />
    {error && <WarningBanner type="error" message={error} />}
    {isManager && pending.length > 0 && <Section title="Applications awaiting review">{pending.map(p => { const s = shifts.find(x => x.id === p.openShiftId); return s && <Card key={p.id} bordered><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold text-navy-100">{name(p.employeeId)} wants to pick up {label(assignment(s.shiftId))}</p><p className="text-xs text-navy-500 mt-1">Applied {time(p.createdAt)} · posted by {name(s.originalEmployeeId)}</p></div><Button size="sm" onClick={() => setReview(p)}>Review</Button></div></Card>; })}</Section>}
    {pool.length > 0 && <Section title="Available shifts">{pool.map(s => { const eligibility = pickupEligibility(s); return <ShiftCard key={s.id} shift={s} apps={forShift(s.id)} employees={employees} assignments={assignments} myId={myId} isManager={isManager} saving={saving} canPick={eligibility.allowed} pickupWarnings={eligibility.warnings} onPick={() => save(() => requestOpenShiftPickup(s.id, myId, eligibility.warnings))} onWithdraw={() => save(() => withdrawOpenShift(s.id, myId))} />; })}</Section>}
    {history.length > 0 && <Section title="History">{history.map(s => <ShiftCard key={s.id} shift={s} apps={forShift(s.id)} employees={employees} assignments={assignments} myId={myId} isManager={isManager} saving={false} canPick={false} pickupWarnings={[]} />)}</Section>}
    {shifts.length === 0 && <EmptyState icon="◯" title="No open shifts" description="When an employee can't attend a shift, they can place it here for someone else to pick up." />}
    <Modal isOpen={placeModal} onClose={() => setPlaceModal(false)} title="Place Shift in Open Pool" footer={<><Button variant="ghost" size="sm" onClick={() => setPlaceModal(false)}>Cancel</Button><Button size="sm" loading={saving} disabled={!shiftId || !reason.trim() || !canPlaceInPool(assignment(shiftId)!)} onClick={() => save(async () => { await createOpenShift({ originalEmployeeId: myId, shiftId, status: 'open', reason, validationWarnings: [], createdAt: new Date().toISOString() }); setPlaceModal(false); setShiftId(''); setReason(''); })}>Place in Pool</Button></>}><div className="bg-amber-900/20 border border-amber-500/20 rounded-lg px-3 py-2 text-xs text-amber-300 mb-4">⚠ Your assignment remains unchanged until a manager approves a pickup.</div><FormField label="Which shift can't you attend?" hint="A shift with more than two scheduled employees cannot be placed in the pool; notify your manager instead."><Select value={shiftId} onChange={e => setShiftId(e.target.value)}><option value="">Select your shift…</option>{assignments.filter(a => a.employeeId === myId).map(a => <option key={a.id} value={a.id} disabled={!canPlaceInPool(a)}>{label(a)}{canPlaceInPool(a) ? '' : ' — More than 2 employees scheduled (contact manager)'}</option>)}</Select></FormField><FormField label="Reason"><Textarea value={reason} onChange={e => setReason(e.target.value)} rows={3} /></FormField></Modal>
    {review && <Modal isOpen onClose={() => { setReview(null); setNote(''); }} title="Review pickup application" footer={<><Button variant="ghost" size="sm" onClick={() => setReview(null)}>Cancel</Button><Button variant="danger" size="sm" loading={saving} onClick={() => save(async () => { await resolveOpenShiftPickupRequest(review.id, false, currentUser!.uid, note.trim()); setReview(null); setNote(''); })}>Decline</Button><Button variant="success" size="sm" loading={saving} onClick={() => save(async () => { await resolveOpenShiftPickupRequest(review.id, true, currentUser!.uid, note.trim()); setReview(null); setNote(''); })}>Approve</Button></>}><p className="text-sm text-navy-300 mb-3"><span className="text-navy-500">Applicant: </span>{name(review.employeeId)}</p>{review.validationWarnings?.map((warning, index) => <WarningBanner key={index} type="warning" message={warning} />)}<FormField label="Decision note" hint="Optional for approval or decline."><Textarea value={note} onChange={e => setNote(e.target.value)} rows={3} placeholder="Explain your decision…" /></FormField></Modal>}
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="text-xs font-mono text-navy-500 uppercase tracking-wide mb-2">{title}</h3><div className="space-y-3">{children}</div></section>; }
function time(value: string) { return new Date(value).toLocaleString(); }
function label(a?: ShiftAssignment) { return a ? `${ICON[a.shiftType]} ${a.shiftType[0].toUpperCase() + a.shiftType.slice(1)} · ${formatDate(a.date)} (${a.hours}h)` : 'Unknown shift'; }
function ShiftCard({ shift, apps, employees, assignments, myId, isManager, saving, canPick, pickupWarnings, onPick, onWithdraw }: { shift: OpenShiftRequest; apps: OpenShiftPickupRequest[]; employees: Employee[]; assignments: ShiftAssignment[]; myId: string; isManager: boolean; saving: boolean; canPick: boolean; pickupWarnings: string[]; onPick?: () => void; onWithdraw?: () => void }) {
  const name = (id: string) => employees.find(e => e.id === id)?.name ?? id; const mine = apps.find(a => a.employeeId === myId); const pending = apps.filter(a => a.status === 'pending').length; const declined = apps.filter(a => a.status === 'rejected').length;
  const statusLabel = shift.status === 'filled' ? 'Filled' : shift.status === 'cancelled' ? 'Withdrawn' : 'Open';
  return <Card bordered><div className="flex items-start justify-between gap-3 mb-2"><p className="text-sm font-semibold text-navy-100">{label(assignments.find(a => a.id === shift.shiftId))}</p><Badge variant={shift.status === 'filled' ? 'approved' : shift.status === 'cancelled' ? 'rejected' : 'info'}>{statusLabel}</Badge></div><p className="text-xs text-navy-400 mb-2"><span className="text-navy-500">Posted by: </span>{name(shift.originalEmployeeId)}</p><p className="text-xs text-navy-400 italic mb-3">“{shift.reason}”</p><div className="text-xs text-navy-400 bg-navy-900 rounded px-2.5 py-2 mb-3"><span className="text-navy-500">Applications: </span>{apps.length} total · {pending} pending · {declined} declined</div>{apps.length > 0 && <div className="border-t border-navy-700 pt-2 mb-3 space-y-1.5">{apps.map(a => <div key={a.id} className={`text-xs text-navy-300 ${a.status === 'rejected' ? 'line-through opacity-70' : ''}`}><span>{name(a.employeeId)}</span><span className="text-navy-500"> · {time(a.createdAt)} · </span><span className={a.status === 'pending' ? 'text-amber-300' : a.status === 'approved' ? 'text-emerald-300' : 'text-rose-300'}>{a.status === 'pending' ? 'Waiting for approval' : a.status}</span>{a.validationWarnings?.map((warning, index) => <span key={index} className="text-amber-300"> — {warning}</span>)}{a.managerNote && <span className="text-navy-500"> — {a.managerNote}</span>}</div>)}</div>}{!isManager && !mine && shift.originalEmployeeId !== myId && shift.status !== 'filled' && pickupWarnings.map((warning, index) => <WarningBanner key={index} type={canPick ? 'warning' : 'error'} message={warning} />)}{mine?.status === 'pending' && <Button size="sm" variant="secondary" disabled fullWidth>Waiting for approval</Button>}{!isManager && !mine && shift.originalEmployeeId !== myId && shift.status !== 'filled' && <Button size="sm" variant="secondary" disabled={!canPick} loading={saving} onClick={onPick} fullWidth>{canPick ? 'Request to Pick Up' : 'Not eligible to pick up'}</Button>}{!isManager && shift.originalEmployeeId === myId && (shift.status === 'open' || shift.status === 'requested') && <Button size="sm" variant="danger" loading={saving} onClick={onWithdraw} fullWidth>Withdraw from Open Pool</Button>}<p className="text-[10px] text-navy-600 font-mono mt-2">Created {time(shift.createdAt)}</p></Card>;
}
